# Generated by Django 2.1.7 on 2019-03-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField(default='10:00')),
                ('priority', models.IntegerField(default=3)),
                ('category', models.CharField(default='None', max_length=50)),
                ('status', models.CharField(default='active', max_length=10)),
            ],
        ),
    ]
